CREATE TABLE IF NOT EXISTS SCALES (
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS SCALE_LEVELS (
    SCALE_ID INT NOT NULL,
    LEVEL INT NOT NULL,
    SHORT_DESC VARCHAR(255) NOT NULL,
    FULL_DESC VARCHAR(1000) NOT NULL,
    PRIMARY KEY(SCALE_ID, LEVEL),    
    FOREIGN KEY(SCALE_ID) REFERENCES SCALES(ID) ON DELETE CASCADE
);

INSERT INTO SCALES(ID,TITLE) VALUES(1,'Funding Readiness Level');
INSERT INTO SCALES(ID,TITLE) VALUES(2,'Customer Readiness Level');
INSERT INTO SCALES(ID,TITLE) VALUES(3,'Technology Readiness Level');
INSERT INTO SCALES(ID,TITLE) VALUES(4,'Team Readiness Level');
INSERT INTO SCALES(ID,TITLE) VALUES(5,'IPR Readiness Level');
INSERT INTO SCALES(ID,TITLE) VALUES(6,'Business Model Readiness Level');

INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,1,'No clear description of initial verification activities.\r\nNo clear view of initial funding needs and funding options.\r\n','Little or no insight into relevant activities and costs to verify potential/feasibility of the idea.\r\nLittle insight into different funding options and funding types.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,2,'Description of initial verification activities.\r\nDefined funding need and funding sources for initial milestones.','Initial activities and costs to verify potential/feasibility if idea is described (e.g. 1-6 months).\r\nThere is a basic plan with funding options for the initial milestones (e.g. 1-6 months).\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,3,'Funding for initial verification plan secured. ','Secured sufficient funding for initial verification/feasibility activities (e.g. 1-6 months).\r\nAwareness of different funding types (own, soft, equity, customer, etc.) and typical pros/cons. \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,4,'Funding for elaborated verification plan secured.','Elaborated plan to verify commercial potential of the idea is in place (e.g. 3-12 months, incl. hypotheses to verify, goals, activities, timeline, funding need). \r\nIdentified relevant funding sources.\r\nSecured sufficient funding to implement substantial part of the verification plan.   \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,5,'First pitch for funding tested on relevant audience.\r\nDefined near term funding need and decided on funding strategy.','Pitch for funding (e.g. investor pitch format) elaborated and tested on relevant audience. \r\nInitial PnL budget & cash flow for coming 12 months in spreadsheet format.\r\nDecided on funding strategy and funding sources to reach a viable business model - based on pros/cons of the different strategies.   \r\nInsight into requirements and consequences of external funding (in particular equity funding) on business model, control, and ownership.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,6,'Improved pitch for funding tested on relevant audience.\r\nInitiated contacts with relevant external funding sources.','Updated/improved pitch for funding has been tested on relevant audience. \r\n3-5 year PnL budget and cash flow for business/project in spreadsheet format that clarifies near and medium term funding need.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,7,'Initial discussions with potential external funding sources.\r\nComplete pitch for funding and supporting material ready.','Discussions with potential external funding sources around a defined offer (how much money, for what, conditions, valuation, etc.).\r\nPitch for funding is complete, tried, and tested, and a business plan (or equivalent) with financial projections, milestone plan etc. is in place. \r\nBasic accounting systems and documentation in place for financial follow-up.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,8,'Term sheet level discussions with one or several external funding sources that show clear interest.','Concrete discussions (term sheet level) with one or several external funding sources that clearly are interested.\r\nAll necessary supporting material for external funding in place (financials, business plan, etc.).\r\nCorrectly established legal entity with ownership structure suitable for the planned funding source (not fragmented or significant parts held by inactive/non-contributing persons).\r\nAll key legal, IPR, financial, and operational documentation and agreements collected and available for external review (due diligence).\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(1,9,'Secured funding for at least 6-12 months of operations.\r\nFinancial monitoring and forecasting system fully implemented.','Secured funding for at least 6-12 month runway according to current business plan/operational plan – the money is on the bank account or predictable recurring revenue.\r\nFully implemented financial monitoring and bookkeeping system for continuous control of current financial status, and good forecast/foresight of future funding needs. \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,1,'Hypothesis of possible needs in the market.','Thinking (yourself) that a possible need/problem or opportunity might exist in a market.\r\nNo clear hypotheses on who customers are, what problems exist, etc. If hypotheses exist they are unclear, speculative, and there is no proof or analysis to support assumptions.\r\nLimited or non-existing knowledge of the market and customers/users.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,2,'Identified specific needs in the market.','Some market research is performed, typically derived from secondary sources.\r\nBrief familiarity with the market, possible customers and their problems/needs, and alternatives.\r\nThere is a first reasonably clear description of the problem/need hypothesis. \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,3,'First market feedback established.','Received feedback from primary market research, i.e. direct contacts with e.g. a few possible users/customers or persons with industry/market knowledge (experts).\r\nA more developed understanding of possible customers and possible customer segments. \r\nThe problem/need hypothesis is clear and updated after customer/user/expert feedback.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,4,'Confirmed problem/need from several customers or users.','The problem/need and its importance is confirmed from multiple customers or users. Numbers are typically limited but depend on B2B/B2C and market structure (e.g. 5-10 in B2B, if market is concentrated 2-5 market leading customers, in B2C higher e.g. 10-20).\r\nCustomer segmentation with initial basic customer profiles in place. \r\nIdentified who the user, paying customer, and decision maker is.\r\nA product/service hypothesis with clear positioning against customer alternatives is defined based on customer/user feedback.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,5,'Established interest and relations with customers.','Customers/users have expressed interest for the product/service and confirmed that it can solve customers’ problems/needs (i.e. initial problem-solution fit).\r\nEstablished relationships with potential target customers/users providing input.\r\nDecided which target customers/segments to focus on first.\r\nDefined first sales pitch and value proposition adapted to target customer/segment.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,6,'Benefits confirmed by first customer testing.','Testing of product/service by customers/users has confirmed the customer value and benefits.\r\nUpdated sales pitch and value proposition based on customer/user feedback.\r\nDefined first sales/user acquisition process and initiated structured sales activities.\r\nIdentified possible partners or key stakeholders relevant to reach customers/users.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,7,'Customers in extended testing or first test sales.\r\nSmall number of active users.','Customer agreements in place - first sales/test sales of early versions of product/service or customers/users engaged in product/service qualifications or extended testing. \r\nSmall number of active users of early versions of product/service.\r\nDiscussions initiated with partners to reach customers/users (when relevant). \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,8,'First commercial sales and implemented sales process. Substantial number of active users.','Market ready product/service sold to customers at/near target market price.\r\nSubstantial number of active users of market ready product/service (initial customer traction).\r\nSales/user acquisition process implemented with dedicated people and support systems (CRM system, etc.). \r\nAgreements in place with first partners to reach customers (when relevant).\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(2,9,'Widespread sales that scale.\r\nLarge number of active users with substantial growth.\r\n','Widespread product deployment, sales to several customers in a repeatable and scalable way (including through partners when relevant).\r\nLarge and substantially growing number of active users (significant customer traction).\r\nCompany focuses on business development, customer acquisition, growth of sales, efforts to build user/customer demand, etc.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,1,'Interesting research results or initial technology idea identified.','Research results with potential benefits or useful applications identified. \r\nVague idea of a technology to be developed.\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,2,'Technology concept and/or application formulated.','A potential technology concept is defined and described.\r\nPractical applications can be defined/researched but are speculative, and no proof or detailed analysis that the technology will work.\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,3,'Proof-of-concept of critical functions and/or characteristics in laboratory.','Tests in the laboratory environment (analytical and/or experimental) of important parameters/features/functions show that the technology concept could work and be feasible. \r\nLaboratory environment = the environment where technology is typically developed, often not the same environment as where it will be used.\r\nActive R&D is initiated to develop the technology further.\r\nThere is a first idea of end-user requirements/specifications and/or use cases.');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,4,'Technology validation in laboratory.','Basic components are integrated and shown to work together and produce desired results in the laboratory environment. \r\nTest results give initial evidence indicating that the technology concept will work (i.e. initial validation). \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,5,'Technology validation in relevant environment.','Basic components are integrated and tested in a more realistic form in a relevant environment. \r\nTest results give evidence indicating that the technology will work (i.e. validation). \r\nRelevant environment = lab or other controlled environment that simulates the most important and most stressing aspects of the operational environment.\r\nMore defined end-user requirements/specifications and/or use cases based on feedback from users.');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,6,'Technology prototype demonstration in relevant environment.','Representative model or prototype of the technology has been shown to actually work in a relevant environment.\r\nRepresentative model = a functional form of the technology, generally reduced in scale, near or at operational specification. \r\nPrototype =  the technology in a form that can be used to evaluate the technical and/or manufacturing feasibility or utility of the final product.\r\nShown to actually work (i.e. demonstration) = meet most of the important performance requirements.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,7,'Technology prototype demonstration in operational environment.','Prototype near or at the complete technology has been shown to actually work in an operational environment.\r\nOperational environment = environment that addresses all the operational requirements and specifications where the technology will be used by the end-users.\r\nComplete end-user requirements/specifications and/or use cases in place.');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,8,'Technology complete and demonstrated in actual operations.','Complete technology has been proven to work in actual operations by first users.\r\nComplete technology = Complete - contains everything the user needs to use it; Functional  - everything works the way it should for the user to solve their problem/need; Compatible - compatible with people, processes, goals, infrastructure, systems, etc. at the user; Producible - possible to produce at a reasonable cost.\r\nProven to work = meet all performance requirements/specifications.\r\nActual operations = implemented by end-users on their own in their day-to-day operations. \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(3,9,'Technology complete and proven in actual operations over time.','Complete technology is scalable and proven to work in actual operations by several users over time. \r\nContinuous development, improvement, optimization of technology and production is ongoing. \r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,1,'Lack of necessary competencies/resources to verify idea.\r\nLittle insight into team needs (typically an individual). \r\n\r\n','Typically an individual lacking necessary competencies in key areas such as tech, business etc.\r\nLittle insight into needed/necessary competencies and other needed resources (e.g. partners, service providers etc.) to verify and develop the idea.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,2,'Limited competencies in place to start verifying the idea.\r\nFirst idea of additional necessary competencies or resources.\r\n','Limited competencies and/or capacity present - typically 1-2 persons.\r\nFirst idea of which additional persons/competencies that could be needed to verify/develop idea.\r\nFirst idea of overall goal for the project.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,3,'Some of necessary competencies in place to verify/develop idea.\r\nDefined needed competencies (and plan for finding them).\r\n','One or several individuals that possess some, but not all, of necessary competencies and capacity to start verifying the idea.\r\nNeeds and gaps in competencies, capacity, and team diversity are identified. \r\nInitial plan is defined for how to find needed prioritized competencies (near-term, <1 year).  \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,4,'A champion is present with clear idea of direction (startup/other way). Several needed competencies in place, initiated plan to complement.','Team (or individual) has a clear idea of how to take the idea to market (startup, IP deal, etc.).\r\nAt least one champion (driver and committed to take the idea forward) is present.\r\nSeveral, but not all, necessary competencies are present, typically multiple individuals. \r\nA plan is in place and initiated to find necessary additional competencies and capacity (described e.g. in a requirement profile), keeping in mind team diversity.\r\nThe team has started discussions on roles, commitment, ownership, etc. going forward.\r\n \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,5,'Initial founding team with main needed competencies and capacity.\r\nTeam agrees on ownership, roles, goals, and visions.\r\n','An initial founding team working together and all spending significant time. The founding team jointly having main needed competencies and capacity to start building this startup.\r\nAligned team with clarified roles, shared goals and visions, and clear commitment (e.g. time spent).\r\nThe team has agreed on their respective shares (signed agreement). Ownership is balanced and incentivizing, and reflects historical and future commitment and contribution.\r\nActivities to get additional competencies and capacity in progress, keeping in mind team diversity.\r\nInitial systems/processes/tools in place to share knowledge and information within the team.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,6,'Technology prototype demonstration in relevant environment.Complementary, diverse, and committed founding team with all necessary competencies and capacity to start building a business.','Complementary and diverse founding team in place, capable of starting to build a business.\r\nAll key competencies and capacity necessary for the near term are present, incl. a clear CEO.\r\nCommitted team where everyone feels responsibility and accountability.\r\nStarted recruitment of advisors and/or board members, keeping in mind board diversity.\r\nAwareness of risks to team performance (conflicts, burn-out/mental health, politics, etc.).\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,7,'Well-functioning team and culture in place. Growth plan for expanding team and building organization over time.','Well-functioning team with clear roles.\r\nGoals, vision, purpose, and culture are clearly articulated and documented to support team and organizational development.\r\nPlan in place for how to build necessary organization and grow the team over longer term (~2 yrs).\r\nProcesses/systems and plan for continuous learning and staff development implemented.\r\nBoard and advisors operational and supporting business and organizational development.\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,8,'Professional organization in place (board, CEO, management, staff).','There is a clear leadership and management team with relevant professional experience.\r\nCompetent and diverse board, and relevant advisors in place and professionally used.\r\nHR policies/processes/responsible in place to assure good HR practices and team diversity.\r\nNecessary recruitments according to longer term plan are ongoing to ascertain relevant competencies, capacity, and diversity in the organization.\r\nAll levels of the organization are properly trained and motivated.\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(4,9,'High performing, well-structured organization at all levels that is maintained, develops, and performs over time.','The organization is high performing and well-functioning (cooperation, social environment, etc.).\r\nAll levels of the organization actively engaged in continuous learning and development.\r\nOrganizational culture, structure, processes etc. are continuously improved and developed. \r\nIncentives/rewards are aligned to motivate the whole organization to reach goals and perform well.\r\nThe management team is maintained, developed and performs over time.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,1,'Hypothesizing on your possible IPR.\r\n\r\n','Hypothesizing that results or ideas might contain some possible form of IPR. \r\nSome ideas on possible IPR may exist, but are speculative.\r\nNo description and documentation of the possible IPR.\r\nLimited knowledge of or unclarity regarding relevant legal aspects (such as ownership or use-rights).\r\nLimited knowledge of uniqueness and the technical field, state-of-the art, publications etc.\r\n\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,2,'Identified different forms of possible IPR that you have/create.\r\nOwnership is clarified and you can use relevant IPR. ','Mapped different forms of IPR that exist or could come up during development (see IPR list).\r\nSpecific ideas for IPR exist, but are not well described and defined.\r\nAgreements related to IP are identified and ownership is clarified. Inventors/creators are clarified. Knowledge of applicable IP policies, potential restrictions in contracts, etc.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,3,'Description of possible key IPR in some detail.\r\nInitial evaluation of potential to protect key IPR.','Considered what forms of IPR are key/most important and could/should be protected.\r\nSufficiently detailed description of possible IPR to evaluate possibility for protection. \r\nEvaluation of protection possibilities via e.g. own searches of publications, state-of-the art solutions etc. in the field.\r\nPossibly initial searches or analysis by professional of relevant prior art or conflicting IPR.\r\n \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,4,'Confirmed that IPR protection is possible and for what.\r\nDecided why to protect certain IPR (business relevance).','Confirmed possibilities for protection of key IPR through searches/analysis by a professional.\r\nAnalyzed (ideally with professional) the key IPR and what the priorities should be for what to protect to create value for the business/project. \r\nPossibly filed first IPR application/registration in some less elaborate form, e.g. own filing of trademark, “provisional” patent application (i.e. not professionally drafted), etc.\r\n\r\n \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,5,'Draft of IPR strategy to create business value is in place.\r\nFiled first formal application/registration of key IPR.\r\n','Draft IPR strategy in place - first analysis and plan (preferably by professional) on how different IPR can be used to protect and be of value for the business. (see e.g. tool KTH IPR Strategy).\r\nFirst complete formal application/registration of key IPR filed in cooperation with professional.\r\nBasic agreements in place to ascertain control of key IPR (e.g. assignments, ownership, etc.). \r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,6,'First complete IPR strategy in place considering different IPR.  \r\nPositive response on filed applications/registrations. ','Complete IPR strategy elaborated (validated by professional) that supports business strategy.\r\nIdentified possible complementary/additional IPR to protect. \r\nInitial assessment of freedom-to-operate with the purpose to understand the IPR landscape in the field (who is active, what key IPR) and if you could be dependent on/stopped by other IPR.\r\nPositive response on applications from authorities, and analysis of response performed.\r\nIf no positive response: analysis performed together with professional with good prospects.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,7,'Filed formal applications/registrations of key IPR in relevant countries/regions according to IPR strategy.','Entered into national/regional phase (US, EU, JP etc.) with key IPR application/registration.\r\nMore complete assessment of freedom-to-operate and clear understanding of dependency on/restriction by other IPR.\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,8,'IPR strategy and management practices fully implemented.\r\nFiled formal applications/registrations of complementary IPR.','IPR strategy is fully implemented. IPR is proactively used to support/protect business, IPR related agreements are professionally managed, process for securing new IPR in place.\r\nKey IPR is granted in first country/region with relevant scope for business.\r\nFiled complementary or additional IPR application(s)/registration(s).\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(5,9,'Strong IPR support and protection for business.\r\nIPR protection granted and maintained in relevant countries.','IPR strategy is proven to support and create value for business.\r\nKey and complementary IPR is granted and maintained in several countries relevant for business.\r\nAgreements in place to access all necessary external IPR.\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,1,'No or unclear hypothesis of possible business idea, market potential, and competition.','Non-existing or vague and unspecific description of the potential business idea, value proposition or business model.\r\n\r\nLittle insight into the market and its potential/size-hypothesizing on possible applications.\r\n\r\nLittle knowledge or insight into competition and alternative solutions.\r\n\r\n\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,2,'First hypothesis of possible business concept (in any format) and identified overall market potential and competition. ','Described the proposed business concept and value proposition in some structured form. \r\n\r\nBrief familiarity with market size, segments, and competitive landscape (listed some competitors/alternatives) – typically derived from secondary sources.\r\n\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,3,'Description of sustainable business model and target market(s), including competition. ','Description of a proposed business model in place (e.g. in canvas format). \r\n\r\nDescription of relevant factors in the business model causing positive and negative contribution to environment and society (see KTH IRL user guide).\r\n\r\nDefined target market(s) and estimates of market size (TAM, SAM).\r\n\r\nDefined competition and identified relevant input from competitive landscape on your business model (competitors’ positioning, business models, prices, etc.). \r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,4,'First calculations indicating economically viable business model.\r\nFirst assessment indicating environmental and social sustainability.  ','First version of simplified P&L projections for proposed business model (main costs, main revenue streams) indicate economic viability (based on own assumptions and guesstimates).\r\n\r\nInitial assessment of positive vs negative contribution indicates environmental and social sustainability, based on own assumptions and guesstimates (see KTH IRL user guide).\r\n\r\n\r\n \r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,5,'Key assumptions in sustainable business model tested on market.\r\n','Received feedback on revenue side of business model (e.g. revenue model, pricing, etc.) from a few potential customers or persons with market knowledge (experts).  \r\n\r\nReceived feedback on cost side of business model (e.g. production, supply chain, etc.) from a few external partners/suppliers/experts.\r\nKey measures to increase positive and decrease negative environmental and social contribution specified in business model (see KTH IRL user guide).\r\n\r\nUpdated P&L projection based on market feedback indicates economic viability.\r\n\r\nTarget market description (target segment(s), TAM, SAM, SOM, and competitive analysis) updated based on market feedback.\r\n \r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,6,'Full sustainable business model tested on customers, partners, suppliers (e.g. by test sales), calculations show economic viability.  ','Complete sustainable business model (cost side and revenue side), including key measures to increase positive and decrease negative environmental and social contribution, is tested in one/a few realistic business scenarios (test sale, pre-order, pilot, tender, etc.).\r\n\r\nComplete financial projections based on feedback from realistic business case show economic viability.\r\n\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,7,'Viability of sustainable business model (pricing, revenue model, etc.) validated by initial commercial sales.','-	First sales/revenue on commercial terms demonstrate willingness to pay from significant number of customers \r\nComplete financial projections validated by first sales/revenue and data.\r\n\r\nAgreements in place with key suppliers, partners, channel partners etc. (aligned with your sustainability expectations) to execute your business model. \r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,8,'Sales and metrics show that sustainable business model is viable.','Sales and other metrics from initial business operations (1-3 years) show sustainable business model holds and can meet internal and external expectations on profit, scalability, and environmental and social impact.\r\n\r\nSales channels and supply chain (aligned with your sustainability expectations) are in place and operational.\r\n\r\nBusiness model is set but is fine-tuned to improve revenue/cost and leverage sustainability. \r\n\r\n\r\n\r\n');
INSERT INTO SCALE_LEVELS(SCALE_ID, LEVEL, SHORT_DESC, FULL_DESC) VALUES(6,9,'Sustainable business model proven to meet internal and external expectations on profit, scalability and impact over time.','Sustainable business model is operational and business meets or exceeds internal and external expectations on profit, growth, scalability, and environmental and social impact.\r\n\r\nCredible systems and metrics in use to track economic, environmental, social performance. \r\n\r\nHistoric data on economic, environmental, and social performance proves viable business which is profitable and sustainable over time.\r\n\r\n\r\n\r\n');